#!/bin/sh -e

set -e

# ref: postinst in sudo package

case "$1" in
configure)

  echo "Installed /opt/face_id_server"
  if [ ! -L /etc/ld.so.conf.d/face_id_server.conf ]; then
    ln -s /opt/face_id_server/config/face_id_server.conf /etc/ld.so.conf.d/face_id_server.conf
    echo "Installed /etc/ld.so.conf.d/face_id_server.conf"
    ldconfig
  fi

  if [ ! -L /lib/systemd/system/face_id_server.service ]; then
    ln -s /opt/face_id_server/service/face_id_server.service /lib/systemd/system/face_id_server.service
    systemctl enable face_id_server
  fi

  if [ ! -L /usr/local/bin/face_id_server ]; then
    ln -s /opt/face_id_server/bin/face_id_server /usr/local/bin/
    echo "Installed /usr/local/bin/face_id_server"
  fi

  # if [ ! -L /usr/local/bin/seeta_face_feature_database_cli ]; then
  #   ln -s /opt/face_id_server/bin/seeta_face_feature_database_cli /usr/local/bin/
  #   echo "Installed /usr/local/bin/seeta_face_feature_database_cli"
  # fi

  if [ ! -d /etc/face_id_server/config ]; then
    mkdir -p /etc/face_id_server/config
    cp /opt/face_id_server/config/config.yaml /etc/face_id_server/config
    echo "Installed /etc/face_id_server/config/config.yaml"
  fi

  ;;

esac
